# Generated by Django 5.2.8 on 2025-11-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ficha',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una ficha'), ('2556678', '2556678'), ('3175010', '3175010'), ('2003120', '2003120'), ('2558341', '2558341'), ('2559123', '2559123'), ('2670689', '2670689'), ('2694501', '2694501'), ('2712345', '2712345'), ('2722890', '2722890'), ('2735678', '2735678'), ('2748901', '2748901'), ('2754321', '2754321'), ('2769876', '2769876'), ('2781122', '2781122'), ('2793344', '2793344'), ('2805566', '2805566'), ('2817788', '2817788'), ('2829900', '2829900'), ('2831234', '2831234'), ('2845678', '2845678')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='programa',
            field=models.CharField(blank=True, choices=[('', 'Seleccione un programa'), ('programacion', 'Programación de Software'), ('electricidad', 'Electricidad Industrial'), ('telecomunicaciones', 'Telecomunicaciones'), ('audiovisual', 'Producción Audiovisual'), ('mantenimiento', 'Mantenimiento Electromecánico'), ('diseno_grafico', 'Diseño Gráfico'), ('contabilidad', 'Contabilidad y Finanzas')], max_length=100, null=True),
        ),
    ]
