# Generated by Django 5.2.8 on 2025-11-23 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_asignatura_clase_especialidad_especialidadasignatura_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='programa',
            table='programa',
        ),
    ]
