# Generated by Django 5.2.8 on 2025-11-25 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_ficha_programa_alter_usuario_ficha_ficha_programa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='duracion_meses',
        ),
    ]
