# Generated by Django 5.2.8 on 2025-11-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_programa_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='Clase',
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
        migrations.DeleteModel(
            name='Especialidadasignatura',
        ),
        migrations.DeleteModel(
            name='Ficha',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='Instructorespecialidad',
        ),
        migrations.DeleteModel(
            name='Programa',
        ),
        migrations.DeleteModel(
            name='Programaficha',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
        migrations.DeleteModel(
            name='Registrorol',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='Salon',
        ),
    ]
