# Generated by Django 5.2.8 on 2025-11-25 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_programa_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=30, help_text='Número máximo de aprendices en la ficha.'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ficha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendices', to='usuarios.ficha'),
        ),
    ]
