# Generated by Django 5.2.8 on 2025-11-25 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_ficha_cupo_maximo_alter_usuario_ficha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Felicitación', 'Felicitación'), ('Llamado de atención verbal', 'Llamado de atención verbal'), ('Llamado de atención escrito', 'Llamado de atención escrito'), ('Sanción', 'Sanción'), ('Deserción', 'Deserción')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aprendiz', models.ForeignKey(limit_choices_to={'rol': 'aprendiz'}, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.ficha')),
                ('instructor', models.ForeignKey(limit_choices_to={'rol': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
